# coding: utf-8

"""
    QRAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import enzona-qr
from enzona-qr.models.payload1 import Payload1  # noqa: E501
from enzona-qr.rest import ApiException


class TestPayload1(unittest.TestCase):
    """Payload1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayload1(self):
        """Test Payload1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = enzona-qr.models.payload1.Payload1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
