# coding: utf-8

"""
    QRAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import enzona-qr
from enzona-qr.api.obtiene_la_informacin_de_un_qr_api import ObtieneLaInformacinDeUnQRApi  # noqa: E501
from enzona-qr.rest import ApiException


class TestObtieneLaInformacinDeUnQRApi(unittest.TestCase):
    """ObtieneLaInformacinDeUnQRApi unit test stubs"""

    def setUp(self):
        self.api = enzona-qr.api.obtiene_la_informacin_de_un_qr_api.ObtieneLaInformacinDeUnQRApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_qr_qr_code_get(self):
        """Test case for qr_qr_code_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
