# coding: utf-8

"""
    QRAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse200(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vendor_identity_code': 'str',
        'create_at': 'datetime',
        'update_at': 'datetime'
    }

    attribute_map = {
        'vendor_identity_code': 'vendor_identity_code',
        'create_at': 'create_at',
        'update_at': 'update_at'
    }

    def __init__(self, vendor_identity_code=None, create_at=None, update_at=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger"""  # noqa: E501

        self._vendor_identity_code = None
        self._create_at = None
        self._update_at = None
        self.discriminator = None

        if vendor_identity_code is not None:
            self.vendor_identity_code = vendor_identity_code
        if create_at is not None:
            self.create_at = create_at
        if update_at is not None:
            self.update_at = update_at

    @property
    def vendor_identity_code(self):
        """Gets the vendor_identity_code of this InlineResponse200.  # noqa: E501


        :return: The vendor_identity_code of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._vendor_identity_code

    @vendor_identity_code.setter
    def vendor_identity_code(self, vendor_identity_code):
        """Sets the vendor_identity_code of this InlineResponse200.


        :param vendor_identity_code: The vendor_identity_code of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._vendor_identity_code = vendor_identity_code

    @property
    def create_at(self):
        """Gets the create_at of this InlineResponse200.  # noqa: E501


        :return: The create_at of this InlineResponse200.  # noqa: E501
        :rtype: datetime
        """
        return self._create_at

    @create_at.setter
    def create_at(self, create_at):
        """Sets the create_at of this InlineResponse200.


        :param create_at: The create_at of this InlineResponse200.  # noqa: E501
        :type: datetime
        """

        self._create_at = create_at

    @property
    def update_at(self):
        """Gets the update_at of this InlineResponse200.  # noqa: E501


        :return: The update_at of this InlineResponse200.  # noqa: E501
        :rtype: datetime
        """
        return self._update_at

    @update_at.setter
    def update_at(self, update_at):
        """Sets the update_at of this InlineResponse200.


        :param update_at: The update_at of this InlineResponse200.  # noqa: E501
        :type: datetime
        """

        self._update_at = update_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
